// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepositoryDependencySync = `-- name: CreateRepositoryDependencySync :one
INSERT INTO repository_dependency_syncs (
    repository_id,
    status,
    trigger,
    error_message,
    started_at,
    finished_at
) VALUES (
    $1,
    $2,
    $3,
    '',
    NOW(),
    NULL
)
RETURNING id, repository_id, status, trigger, error_message, started_at, finished_at, created_at, updated_at
`

type CreateRepositoryDependencySyncParams struct {
	RepositoryID int64  `json:"repository_id"`
	Status       string `json:"status"`
	Trigger      string `json:"trigger"`
}

func (q *Queries) CreateRepositoryDependencySync(ctx context.Context, arg CreateRepositoryDependencySyncParams) (RepositoryDependencySync, error) {
	row := q.db.QueryRow(ctx, createRepositoryDependencySync, arg.RepositoryID, arg.Status, arg.Trigger)
	var i RepositoryDependencySync
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Trigger,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepositoryDependenciesByRepo = `-- name: DeleteRepositoryDependenciesByRepo :exec
DELETE FROM repository_dependencies
WHERE repository_id = $1
`

func (q *Queries) DeleteRepositoryDependenciesByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRepositoryDependenciesByRepo, repositoryID)
	return err
}

const deleteRepositoryDependencyFilesByRepo = `-- name: DeleteRepositoryDependencyFilesByRepo :exec
DELETE FROM repository_dependency_files
WHERE repository_id = $1
`

func (q *Queries) DeleteRepositoryDependencyFilesByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRepositoryDependencyFilesByRepo, repositoryID)
	return err
}

const listDependencyEdgesByFromVersion = `-- name: ListDependencyEdgesByFromVersion :many
SELECT
    dvd.id,
    dvd.from_version_id,
    dvd.to_version_id,
    dvd.dependency_type,
    dvd.version_spec,
    child_package.display_name AS child_name,
    child_package.manager AS child_manager,
    child_package.registry AS child_registry,
    child_version.version AS child_version,
    child_version.creator AS child_creator,
    child_version.description AS child_description,
    child_version.license AS child_license,
    child_version.homepage AS child_homepage,
    child_version.repository_url AS child_repository_url,
    child_version.registry_url AS child_registry_url,
    child_version.released_at AS child_released_at
FROM dependency_version_dependencies dvd
INNER JOIN dependency_package_versions child_version ON child_version.id = dvd.to_version_id
INNER JOIN dependency_packages child_package ON child_package.id = child_version.package_id
WHERE dvd.from_version_id = $1
ORDER BY child_package.display_name
`

type ListDependencyEdgesByFromVersionRow struct {
	ID                 int64              `json:"id"`
	FromVersionID      int64              `json:"from_version_id"`
	ToVersionID        int64              `json:"to_version_id"`
	DependencyType     string             `json:"dependency_type"`
	VersionSpec        string             `json:"version_spec"`
	ChildName          string             `json:"child_name"`
	ChildManager       string             `json:"child_manager"`
	ChildRegistry      string             `json:"child_registry"`
	ChildVersion       string             `json:"child_version"`
	ChildCreator       string             `json:"child_creator"`
	ChildDescription   string             `json:"child_description"`
	ChildLicense       string             `json:"child_license"`
	ChildHomepage      string             `json:"child_homepage"`
	ChildRepositoryUrl string             `json:"child_repository_url"`
	ChildRegistryUrl   string             `json:"child_registry_url"`
	ChildReleasedAt    pgtype.Timestamptz `json:"child_released_at"`
}

func (q *Queries) ListDependencyEdgesByFromVersion(ctx context.Context, fromVersionID int64) ([]ListDependencyEdgesByFromVersionRow, error) {
	rows, err := q.db.Query(ctx, listDependencyEdgesByFromVersion, fromVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDependencyEdgesByFromVersionRow
	for rows.Next() {
		var i ListDependencyEdgesByFromVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.FromVersionID,
			&i.ToVersionID,
			&i.DependencyType,
			&i.VersionSpec,
			&i.ChildName,
			&i.ChildManager,
			&i.ChildRegistry,
			&i.ChildVersion,
			&i.ChildCreator,
			&i.ChildDescription,
			&i.ChildLicense,
			&i.ChildHomepage,
			&i.ChildRepositoryUrl,
			&i.ChildRegistryUrl,
			&i.ChildReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRepositoryDependencySync = `-- name: ListLatestRepositoryDependencySync :many
SELECT id, repository_id, status, trigger, error_message, started_at, finished_at, created_at, updated_at
FROM repository_dependency_syncs
WHERE repository_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) ListLatestRepositoryDependencySync(ctx context.Context, repositoryID int64) ([]RepositoryDependencySync, error) {
	rows, err := q.db.Query(ctx, listLatestRepositoryDependencySync, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryDependencySync
	for rows.Next() {
		var i RepositoryDependencySync
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Status,
			&i.Trigger,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryDependenciesDetailed = `-- name: ListRepositoryDependenciesDetailed :many
SELECT
    rd.id,
    rd.repository_id,
    rd.package_id,
    rd.source_file,
    rd.scope,
    rd.version_spec,
    rd.resolved_version_id,
    dp.manager,
    dp.registry,
    dp.display_name,
    dpv.version AS resolved_version,
    dpv.creator,
    dpv.description,
    dpv.license,
    dpv.homepage,
    dpv.repository_url,
    dpv.registry_url,
    dpv.released_at,
    rd.created_at,
    rd.updated_at
FROM repository_dependencies rd
INNER JOIN dependency_packages dp ON dp.id = rd.package_id
LEFT JOIN dependency_package_versions dpv ON dpv.id = rd.resolved_version_id
WHERE rd.repository_id = $1
ORDER BY dp.manager, dp.display_name
`

type ListRepositoryDependenciesDetailedRow struct {
	ID                int64              `json:"id"`
	RepositoryID      int64              `json:"repository_id"`
	PackageID         int64              `json:"package_id"`
	SourceFile        string             `json:"source_file"`
	Scope             string             `json:"scope"`
	VersionSpec       string             `json:"version_spec"`
	ResolvedVersionID pgtype.Int8        `json:"resolved_version_id"`
	Manager           string             `json:"manager"`
	Registry          string             `json:"registry"`
	DisplayName       string             `json:"display_name"`
	ResolvedVersion   pgtype.Text        `json:"resolved_version"`
	Creator           pgtype.Text        `json:"creator"`
	Description       pgtype.Text        `json:"description"`
	License           pgtype.Text        `json:"license"`
	Homepage          pgtype.Text        `json:"homepage"`
	RepositoryUrl     pgtype.Text        `json:"repository_url"`
	RegistryUrl       pgtype.Text        `json:"registry_url"`
	ReleasedAt        pgtype.Timestamptz `json:"released_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRepositoryDependenciesDetailed(ctx context.Context, repositoryID int64) ([]ListRepositoryDependenciesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listRepositoryDependenciesDetailed, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoryDependenciesDetailedRow
	for rows.Next() {
		var i ListRepositoryDependenciesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.PackageID,
			&i.SourceFile,
			&i.Scope,
			&i.VersionSpec,
			&i.ResolvedVersionID,
			&i.Manager,
			&i.Registry,
			&i.DisplayName,
			&i.ResolvedVersion,
			&i.Creator,
			&i.Description,
			&i.License,
			&i.Homepage,
			&i.RepositoryUrl,
			&i.RegistryUrl,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryDependencyFiles = `-- name: ListRepositoryDependencyFiles :many
SELECT id, repository_id, path, file, manager, registry, created_at, updated_at
FROM repository_dependency_files
WHERE repository_id = $1
ORDER BY path
`

func (q *Queries) ListRepositoryDependencyFiles(ctx context.Context, repositoryID int64) ([]RepositoryDependencyFile, error) {
	rows, err := q.db.Query(ctx, listRepositoryDependencyFiles, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryDependencyFile
	for rows.Next() {
		var i RepositoryDependencyFile
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Path,
			&i.File,
			&i.Manager,
			&i.Registry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepositoryDependencySyncFailed = `-- name: MarkRepositoryDependencySyncFailed :exec
UPDATE repository_dependency_syncs
SET status = 'failed',
    error_message = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkRepositoryDependencySyncFailedParams struct {
	ID           int64  `json:"id"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) MarkRepositoryDependencySyncFailed(ctx context.Context, arg MarkRepositoryDependencySyncFailedParams) error {
	_, err := q.db.Exec(ctx, markRepositoryDependencySyncFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markRepositoryDependencySyncSuccess = `-- name: MarkRepositoryDependencySyncSuccess :exec
UPDATE repository_dependency_syncs
SET status = 'success',
    error_message = '',
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRepositoryDependencySyncSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRepositoryDependencySyncSuccess, id)
	return err
}

const upsertDependencyPackage = `-- name: UpsertDependencyPackage :one
INSERT INTO dependency_packages (
    manager,
    registry,
    normalized_name,
    display_name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (manager, registry, normalized_name)
DO UPDATE SET
    display_name = EXCLUDED.display_name,
    updated_at = NOW()
RETURNING id, manager, registry, normalized_name, display_name, created_at, updated_at
`

type UpsertDependencyPackageParams struct {
	Manager        string `json:"manager"`
	Registry       string `json:"registry"`
	NormalizedName string `json:"normalized_name"`
	DisplayName    string `json:"display_name"`
}

func (q *Queries) UpsertDependencyPackage(ctx context.Context, arg UpsertDependencyPackageParams) (DependencyPackage, error) {
	row := q.db.QueryRow(ctx, upsertDependencyPackage,
		arg.Manager,
		arg.Registry,
		arg.NormalizedName,
		arg.DisplayName,
	)
	var i DependencyPackage
	err := row.Scan(
		&i.ID,
		&i.Manager,
		&i.Registry,
		&i.NormalizedName,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDependencyPackageVersion = `-- name: UpsertDependencyPackageVersion :one
INSERT INTO dependency_package_versions (
    package_id,
    version,
    creator,
    description,
    license,
    homepage,
    repository_url,
    registry_url,
    released_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (package_id, version)
DO UPDATE SET
    creator = EXCLUDED.creator,
    description = EXCLUDED.description,
    license = EXCLUDED.license,
    homepage = EXCLUDED.homepage,
    repository_url = EXCLUDED.repository_url,
    registry_url = EXCLUDED.registry_url,
    released_at = EXCLUDED.released_at,
    updated_at = NOW()
RETURNING id, package_id, version, creator, description, license, homepage, repository_url, registry_url, released_at, created_at, updated_at
`

type UpsertDependencyPackageVersionParams struct {
	PackageID     int64              `json:"package_id"`
	Version       string             `json:"version"`
	Creator       string             `json:"creator"`
	Description   string             `json:"description"`
	License       string             `json:"license"`
	Homepage      string             `json:"homepage"`
	RepositoryUrl string             `json:"repository_url"`
	RegistryUrl   string             `json:"registry_url"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) UpsertDependencyPackageVersion(ctx context.Context, arg UpsertDependencyPackageVersionParams) (DependencyPackageVersion, error) {
	row := q.db.QueryRow(ctx, upsertDependencyPackageVersion,
		arg.PackageID,
		arg.Version,
		arg.Creator,
		arg.Description,
		arg.License,
		arg.Homepage,
		arg.RepositoryUrl,
		arg.RegistryUrl,
		arg.ReleasedAt,
	)
	var i DependencyPackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.Creator,
		&i.Description,
		&i.License,
		&i.Homepage,
		&i.RepositoryUrl,
		&i.RegistryUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDependencyVersionDependency = `-- name: UpsertDependencyVersionDependency :exec
INSERT INTO dependency_version_dependencies (
    from_version_id,
    to_version_id,
    dependency_type,
    version_spec
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (from_version_id, to_version_id, dependency_type)
DO UPDATE SET
    version_spec = EXCLUDED.version_spec,
    updated_at = NOW()
`

type UpsertDependencyVersionDependencyParams struct {
	FromVersionID  int64  `json:"from_version_id"`
	ToVersionID    int64  `json:"to_version_id"`
	DependencyType string `json:"dependency_type"`
	VersionSpec    string `json:"version_spec"`
}

func (q *Queries) UpsertDependencyVersionDependency(ctx context.Context, arg UpsertDependencyVersionDependencyParams) error {
	_, err := q.db.Exec(ctx, upsertDependencyVersionDependency,
		arg.FromVersionID,
		arg.ToVersionID,
		arg.DependencyType,
		arg.VersionSpec,
	)
	return err
}

const upsertRepositoryDependency = `-- name: UpsertRepositoryDependency :exec
INSERT INTO repository_dependencies (
    repository_id,
    package_id,
    source_file,
    scope,
    version_spec,
    resolved_version_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (repository_id, package_id, source_file, scope, version_spec)
DO UPDATE SET
    resolved_version_id = EXCLUDED.resolved_version_id,
    updated_at = NOW()
`

type UpsertRepositoryDependencyParams struct {
	RepositoryID      int64       `json:"repository_id"`
	PackageID         int64       `json:"package_id"`
	SourceFile        string      `json:"source_file"`
	Scope             string      `json:"scope"`
	VersionSpec       string      `json:"version_spec"`
	ResolvedVersionID pgtype.Int8 `json:"resolved_version_id"`
}

func (q *Queries) UpsertRepositoryDependency(ctx context.Context, arg UpsertRepositoryDependencyParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryDependency,
		arg.RepositoryID,
		arg.PackageID,
		arg.SourceFile,
		arg.Scope,
		arg.VersionSpec,
		arg.ResolvedVersionID,
	)
	return err
}

const upsertRepositoryDependencyFile = `-- name: UpsertRepositoryDependencyFile :exec
INSERT INTO repository_dependency_files (
    repository_id,
    path,
    file,
    manager,
    registry
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (repository_id, path)
DO UPDATE SET
    file = EXCLUDED.file,
    manager = EXCLUDED.manager,
    registry = EXCLUDED.registry,
    updated_at = NOW()
`

type UpsertRepositoryDependencyFileParams struct {
	RepositoryID int64  `json:"repository_id"`
	Path         string `json:"path"`
	File         string `json:"file"`
	Manager      string `json:"manager"`
	Registry     string `json:"registry"`
}

func (q *Queries) UpsertRepositoryDependencyFile(ctx context.Context, arg UpsertRepositoryDependencyFileParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryDependencyFile,
		arg.RepositoryID,
		arg.Path,
		arg.File,
		arg.Manager,
		arg.Registry,
	)
	return err
}
