// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package db

import (
	"context"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (
  user_id,
  hostname,
  status,
  verification_token,
  dns_record_type,
  dns_record_name,
  dns_record_value
) VALUES (
  $1,
  $2,
  'pending_dns',
  $3,
  $4,
  $5,
  $6
)
RETURNING id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
`

type CreateCustomDomainParams struct {
	UserID            int64  `json:"user_id"`
	Hostname          string `json:"hostname"`
	VerificationToken string `json:"verification_token"`
	DnsRecordType     string `json:"dns_record_type"`
	DnsRecordName     string `json:"dns_record_name"`
	DnsRecordValue    string `json:"dns_record_value"`
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain,
		arg.UserID,
		arg.Hostname,
		arg.VerificationToken,
		arg.DnsRecordType,
		arg.DnsRecordName,
		arg.DnsRecordValue,
	)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserCustomDomain = `-- name: DeleteUserCustomDomain :execrows
DELETE FROM custom_domains
WHERE id = $1 AND user_id = $2
`

type DeleteUserCustomDomainParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserCustomDomain(ctx context.Context, arg DeleteUserCustomDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserCustomDomain, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomDomainByHostname = `-- name: GetCustomDomainByHostname :one
SELECT id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
FROM custom_domains
WHERE hostname = $1
`

func (q *Queries) GetCustomDomainByHostname(ctx context.Context, hostname string) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByHostname, hostname)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCustomDomainByID = `-- name: GetUserCustomDomainByID :one
SELECT id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
FROM custom_domains
WHERE id = $1 AND user_id = $2
`

type GetUserCustomDomainByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserCustomDomainByID(ctx context.Context, arg GetUserCustomDomainByIDParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getUserCustomDomainByID, arg.ID, arg.UserID)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCustomDomains = `-- name: ListActiveCustomDomains :many
SELECT id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
FROM custom_domains
WHERE status = 'active'
ORDER BY id ASC
`

func (q *Queries) ListActiveCustomDomains(ctx context.Context) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listActiveCustomDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.DnsRecordType,
			&i.DnsRecordName,
			&i.DnsRecordValue,
			&i.LastError,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCustomDomains = `-- name: ListUserCustomDomains :many
SELECT id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
FROM custom_domains
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserCustomDomains(ctx context.Context, userID int64) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listUserCustomDomains, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.DnsRecordType,
			&i.DnsRecordName,
			&i.DnsRecordValue,
			&i.LastError,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomDomainActive = `-- name: MarkCustomDomainActive :one
UPDATE custom_domains
SET status = 'active',
    last_error = '',
    verified_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
`

func (q *Queries) MarkCustomDomainActive(ctx context.Context, id int64) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainActive, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCustomDomainError = `-- name: MarkCustomDomainError :one
UPDATE custom_domains
SET status = 'error',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
`

type MarkCustomDomainErrorParams struct {
	ID        int64  `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) MarkCustomDomainError(ctx context.Context, arg MarkCustomDomainErrorParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainError, arg.ID, arg.LastError)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCustomDomainPendingDNS = `-- name: MarkCustomDomainPendingDNS :one
UPDATE custom_domains
SET status = 'pending_dns',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, hostname, status, verification_token, dns_record_type, dns_record_name, dns_record_value, last_error, verified_at, created_at, updated_at
`

type MarkCustomDomainPendingDNSParams struct {
	ID        int64  `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) MarkCustomDomainPendingDNS(ctx context.Context, arg MarkCustomDomainPendingDNSParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainPendingDNS, arg.ID, arg.LastError)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.DnsRecordType,
		&i.DnsRecordName,
		&i.DnsRecordValue,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
