// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	GithubRepoID  int64              `json:"github_repo_id"`
	Name          string             `json:"name"`
	FullName      string             `json:"full_name"`
	Private       bool               `json:"private"`
	DefaultBranch string             `json:"default_branch"`
	HtmlUrl       string             `json:"html_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	GithubID  int64              `json:"github_id"`
	Login     string             `json:"login"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	AvatarUrl string             `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserOauthToken struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	AccessToken string             `json:"access_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
