// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DependencyPackage struct {
	ID             int64              `json:"id"`
	Manager        string             `json:"manager"`
	Registry       string             `json:"registry"`
	NormalizedName string             `json:"normalized_name"`
	DisplayName    string             `json:"display_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DependencyPackageVersion struct {
	ID            int64              `json:"id"`
	PackageID     int64              `json:"package_id"`
	Version       string             `json:"version"`
	Creator       string             `json:"creator"`
	Description   string             `json:"description"`
	License       string             `json:"license"`
	Homepage      string             `json:"homepage"`
	RepositoryUrl string             `json:"repository_url"`
	RegistryUrl   string             `json:"registry_url"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DependencyVersionDependency struct {
	ID             int64              `json:"id"`
	FromVersionID  int64              `json:"from_version_id"`
	ToVersionID    int64              `json:"to_version_id"`
	DependencyType string             `json:"dependency_type"`
	VersionSpec    string             `json:"version_spec"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Repository struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	GithubRepoID  int64              `json:"github_repo_id"`
	Name          string             `json:"name"`
	FullName      string             `json:"full_name"`
	Private       bool               `json:"private"`
	DefaultBranch string             `json:"default_branch"`
	HtmlUrl       string             `json:"html_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependency struct {
	ID                int64              `json:"id"`
	RepositoryID      int64              `json:"repository_id"`
	PackageID         int64              `json:"package_id"`
	SourceFile        string             `json:"source_file"`
	Scope             string             `json:"scope"`
	VersionSpec       string             `json:"version_spec"`
	ResolvedVersionID pgtype.Int8        `json:"resolved_version_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependencyFile struct {
	ID           int64              `json:"id"`
	RepositoryID int64              `json:"repository_id"`
	Path         string             `json:"path"`
	File         string             `json:"file"`
	Manager      string             `json:"manager"`
	Registry     string             `json:"registry"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependencySync struct {
	ID           int64              `json:"id"`
	RepositoryID int64              `json:"repository_id"`
	Status       string             `json:"status"`
	Trigger      string             `json:"trigger"`
	ErrorMessage string             `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	GithubID  int64              `json:"github_id"`
	Login     string             `json:"login"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	AvatarUrl string             `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGithubInstallation struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	InstallationID int64              `json:"installation_id"`
	AppSlug        string             `json:"app_slug"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	HtmlUrl        string             `json:"html_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserOauthToken struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	AccessToken string             `json:"access_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
