// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDependencyEdgesByFromVersion(ctx context.Context, fromVersionID int64) (int64, error)
	CountRepositoryDependenciesByRepo(ctx context.Context, repositoryID int64) (int64, error)
	CountRepositoryDependencyFilesByRepo(ctx context.Context, repositoryID int64) (int64, error)
	CountRepositoryDependencySyncByStatus(ctx context.Context, status string) (int64, error)
	CountRepositoryDependencySyncFailedSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error)
	CountRepositoryDependencySyncSuccessSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error)
	CreateRepositoryDependencySync(ctx context.Context, arg CreateRepositoryDependencySyncParams) (RepositoryDependencySync, error)
	CreateServiceStatusSnapshot(ctx context.Context, arg CreateServiceStatusSnapshotParams) error
	DeleteRepositoryDependenciesByRepo(ctx context.Context, repositoryID int64) error
	DeleteRepositoryDependencyFilesByRepo(ctx context.Context, repositoryID int64) error
	DeleteUserRepositories(ctx context.Context, userID int64) error
	GetDependencyPackageByKey(ctx context.Context, arg GetDependencyPackageByKeyParams) (DependencyPackage, error)
	GetDependencyPackageVersionByPackageAndVersion(ctx context.Context, arg GetDependencyPackageVersionByPackageAndVersionParams) (DependencyPackageVersion, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserOAuthToken(ctx context.Context, arg GetUserOAuthTokenParams) (UserOauthToken, error)
	ListActiveRepositoryDependencySync(ctx context.Context, repositoryID int64) ([]RepositoryDependencySync, error)
	ListDependencyEdgesByFromVersion(ctx context.Context, fromVersionID int64) ([]ListDependencyEdgesByFromVersionRow, error)
	ListLatestRepositoryDependencySync(ctx context.Context, repositoryID int64) ([]RepositoryDependencySync, error)
	ListLatestServiceStatusSnapshots(ctx context.Context) ([]ServiceStatusSnapshot, error)
	ListRepositoryDependenciesDetailed(ctx context.Context, repositoryID int64) ([]ListRepositoryDependenciesDetailedRow, error)
	ListRepositoryDependencyFiles(ctx context.Context, repositoryID int64) ([]RepositoryDependencyFile, error)
	ListUserGitHubInstallations(ctx context.Context, userID int64) ([]UserGithubInstallation, error)
	ListUserRepositories(ctx context.Context, userID int64) ([]Repository, error)
	MarkRepositoryDependencySyncFailed(ctx context.Context, arg MarkRepositoryDependencySyncFailedParams) error
	MarkRepositoryDependencySyncRunning(ctx context.Context, id int64) error
	MarkRepositoryDependencySyncSuccess(ctx context.Context, id int64) error
	UpsertDependencyPackage(ctx context.Context, arg UpsertDependencyPackageParams) (DependencyPackage, error)
	UpsertDependencyPackageVersion(ctx context.Context, arg UpsertDependencyPackageVersionParams) (DependencyPackageVersion, error)
	UpsertDependencyVersionDependency(ctx context.Context, arg UpsertDependencyVersionDependencyParams) error
	UpsertGitHubUser(ctx context.Context, arg UpsertGitHubUserParams) (User, error)
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error
	UpsertRepositoryDependency(ctx context.Context, arg UpsertRepositoryDependencyParams) error
	UpsertRepositoryDependencyFile(ctx context.Context, arg UpsertRepositoryDependencyFileParams) error
	UpsertUserGitHubInstallation(ctx context.Context, arg UpsertUserGitHubInstallationParams) error
	UpsertUserOAuthToken(ctx context.Context, arg UpsertUserOAuthTokenParams) error
}

var _ Querier = (*Queries)(nil)
