// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRepositoryDependencySyncByStatus = `-- name: CountRepositoryDependencySyncByStatus :one
SELECT COUNT(*)
FROM repository_dependency_syncs
WHERE status = $1
`

func (q *Queries) CountRepositoryDependencySyncByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryDependencySyncByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepositoryDependencySyncFailedSince = `-- name: CountRepositoryDependencySyncFailedSince :one
SELECT COUNT(*)
FROM repository_dependency_syncs
WHERE status = 'failed'
  AND finished_at >= $1
`

func (q *Queries) CountRepositoryDependencySyncFailedSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryDependencySyncFailedSince, finishedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepositoryDependencySyncSuccessSince = `-- name: CountRepositoryDependencySyncSuccessSince :one
SELECT COUNT(*)
FROM repository_dependency_syncs
WHERE status = 'success'
  AND finished_at >= $1
`

func (q *Queries) CountRepositoryDependencySyncSuccessSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryDependencySyncSuccessSince, finishedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceStatusSnapshot = `-- name: CreateServiceStatusSnapshot :exec
INSERT INTO service_status_snapshots (
    service,
    status,
    latency_ms,
    uptime_pct,
    note,
    checked_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateServiceStatusSnapshotParams struct {
	Service   string             `json:"service"`
	Status    string             `json:"status"`
	LatencyMs int32              `json:"latency_ms"`
	UptimePct float64            `json:"uptime_pct"`
	Note      string             `json:"note"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) CreateServiceStatusSnapshot(ctx context.Context, arg CreateServiceStatusSnapshotParams) error {
	_, err := q.db.Exec(ctx, createServiceStatusSnapshot,
		arg.Service,
		arg.Status,
		arg.LatencyMs,
		arg.UptimePct,
		arg.Note,
		arg.CheckedAt,
	)
	return err
}

const listLatestServiceStatusSnapshots = `-- name: ListLatestServiceStatusSnapshots :many
SELECT DISTINCT ON (service)
    id,
    service,
    status,
    latency_ms,
    uptime_pct,
    note,
    checked_at,
    created_at
FROM service_status_snapshots
ORDER BY service, checked_at DESC
`

func (q *Queries) ListLatestServiceStatusSnapshots(ctx context.Context) ([]ServiceStatusSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestServiceStatusSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceStatusSnapshot
	for rows.Next() {
		var i ServiceStatusSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Status,
			&i.LatencyMs,
			&i.UptimePct,
			&i.Note,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
